name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci 

  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v1

      - name: Run Build
        run: npm run build

  jest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: npm test
      
      - name: Run Lint Check
        run: npm run lint

  jsdoc:
    runs-on: ubuntu-latest
    needs: [jest]
    steps:
      - uses: actions/checkout@v1

      - name: Run JSDoc
        run: npm run doc
