name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Run Tests
        run: |
          npm ci 
          npm test

      - name: Run Build
        run: npm run build
          
      - name: Run Lint Check
        run: npm run lint

      - name: Run JSDoc
        run: npm run doc
